name: python-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: python-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.12.2" ]
    steps:
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
        id: python

      - name: Check out code into the Python module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test and generate code coverage
        run: |
          make test

      - name: build
        run: |
          make build

  release:
    name: semantic-release
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"
        id: python
      - name: Check out code into the Python module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.2
            @semantic-release/changelog@6.0.1
            @semantic-release/commit-analyzer@12.0.0
            @semantic-release/release-notes-generator@13.0.0
            semantic-release-pypi@3.0.0